name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          # Pasta onde a imagem foi gerada
          build_dir: dist
          # Branch onde a imagem será salva
          target_branch: output
        # O 'env:' fica AQUI, fora do 'with:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
